Repository jmshrv/finamp, pull requests merged in 2025-05, with the labels that each got.

#1134 Allow clearing the queue from within the queue
  lib/components/AlbumScreen/track_menu.dart
  lib/components/PlayerScreen/player_buttons_more.dart
  lib/components/PlayerScreen/queue_list.dart
  lib/l10n/app_en.arb
Labels: enhancement, redesign-beta, hackathon

#1176 New Genre Screen
  lib/components/AlbumScreen/download_button.dart
  lib/components/AlbumScreen/item_info.dart
  lib/components/AlbumScreen/track_list_tile.dart
  lib/components/AlbumScreen/track_menu.dart
  lib/components/ArtistScreen/artist_item_info.dart
  lib/components/ArtistScreen/artist_screen_content.dart
  lib/components/ArtistScreen/artist_screen_content_flexible_space_bar.dart
  lib/components/DownloadsScreen/downloaded_items_list.dart
  lib/components/GenreScreen/genre_count_column.dart
  lib/components/GenreScreen/genre_screen_content.dart
  lib/components/LayoutSettingsScreen/show_artists_top_tracks.dart
  lib/components/MusicScreen/album_item.dart
  lib/components/MusicScreen/album_item_list_tile.dart
  lib/components/MusicScreen/music_screen_tab_view.dart
  lib/components/MusicScreen/sort_by_menu_button.dart
  lib/components/MusicScreen/sort_order_button.dart
  lib/components/PlayerScreen/genre_chip.dart
  lib/components/album_list_tile.dart
  lib/components/albums_sliver_list.dart
  lib/components/curated_item_filter_row.dart
  lib/components/curated_item_sections.dart
  lib/components/icon_and_text.dart
  lib/hive_registrar.g.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/models/finamp_models.dart
  lib/models/finamp_models.g.dart
  lib/screens/artist_screen.dart
  lib/screens/artist_settings_screen.dart
  lib/screens/genre_screen.dart
  lib/screens/genre_settings_screen.dart
  lib/screens/layout_settings_screen.dart
  lib/screens/music_screen.dart
  lib/screens/tabs_settings_screen.dart
  lib/services/android_auto_helper.dart
  lib/services/artist_screen_provider.dart
  lib/services/artist_screen_provider.g.dart
  lib/services/audio_service_helper.dart
  lib/services/downloads_service.dart
  lib/services/downloads_service_backend.dart
  lib/services/finamp_settings_helper.dart
  lib/services/finamp_settings_helper.g.dart
  lib/services/genre_screen_provider.dart
  lib/services/genre_screen_provider.g.dart
  lib/services/jellyfin_api.chopper.dart
  lib/services/jellyfin_api.dart
  lib/services/jellyfin_api_helper.dart
Labels: enhancement, feature, design, redesign-beta

#1150 Tap to enlarge `AlbumImage` on `AlbumScreen`
  lib/components/AlbumScreen/album_screen_content_flexible_space_bar.dart
  lib/components/AlbumScreen/track_menu.dart
  lib/components/ArtistScreen/artist_screen_content_flexible_space_bar.dart
  lib/components/album_image.dart
Labels: redesign-beta, hackathon
