Repository jmshrv/finamp, pull requests merged in 2025-07, with the labels that each got.

#1275 Server Discovery Emulation & Quick Connect Authorization
  lib/color_schemes.g.dart
  lib/components/AddToPlaylistScreen/add_to_playlist_list.dart
  lib/components/AlbumScreen/sleep_timer_menu.dart
  lib/components/AlbumScreen/speed_menu.dart
  lib/components/AlbumScreen/track_menu.dart
  lib/components/LoginScreen/login_flow.dart
  lib/components/LoginScreen/login_server_selection_page.dart
  lib/components/LoginScreen/login_user_selection_page.dart
  lib/components/themed_bottom_sheet.dart
  lib/components/toggleable_list_tile.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/menus/components/menuEntries/menu_entry.dart
  lib/menus/music_screen_drawer.dart
  lib/menus/output_menu.dart
  lib/menus/playlist_actions_menu.dart
  lib/menus/quick_connect_authorization_menu.dart
  lib/menus/server_sharing_menu.dart
  lib/models/jellyfin_models.dart
  lib/screens/lyrics_screen.dart
  lib/screens/settings_screen.dart
  lib/services/censored_log.dart
  lib/services/jellyfin_api.chopper.dart
  lib/services/jellyfin_api.dart
  lib/services/jellyfin_api_helper.dart
  lib/services/server_client_discovery_service.dart
  lib/services/theme_provider.dart
Labels: feature, design, redesign-beta, accessibility

#1276 Add support for Android user-installed certificates
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/network_security_config.xml
  lib/main.dart
  lib/services/jellyfin_api_helper.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, android, redesign-beta, os-integration, upstream issue

#1299 fix: Small Fix for showing the selected Libraries consistently in settings page
  flake.lock
  flake.nix
  lib/screens/view_selector.dart
Labels: enhancement, redesign-beta
