Repository jmshrv/finamp, pull requests merged in 2025-04, with the labels that each got.

#1142 Fix hang on splash screen when resuming app via notification
  android/app/build.gradle
  lib/main.dart
Labels: bug, high priority, android, redesign-beta, os-integration, hackathon

#1144 add opus and flac transcoding
  lib/components/PlayerScreen/feature_chips.dart
  lib/hive_registrar.g.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/models/finamp_models.dart
  lib/models/finamp_models.g.dart
  lib/screens/transcoding_settings_screen.dart
  lib/services/finamp_settings_helper.dart
  lib/services/finamp_settings_helper.g.dart
  lib/services/queue_service.dart
Labels: enhancement, playback, hackathon

#1154 Wrong Navigation when Deleting
  lib/components/AlbumScreen/album_screen_content.dart
  lib/components/AlbumScreen/track_menu.dart
Labels: hackathon

#1148 fix: playback fails to resume from media notification after app is killed (android)
  lib/main.dart
  lib/services/queue_service.dart
Labels: playback, playback reporting, redesign-beta, os-integration, hackathon

#850 Add "Play On" receiver compatibility
  android/app/src/main/kotlin/com/unicornsonlsd/finamp/MainActivity.kt
  lib/components/Buttons/simple_button.dart
  lib/components/LoginScreen/login_flow.dart
  lib/components/PlaybackReportingSettingsScreen/enable_playon_toggle.dart
  lib/components/PlaybackReportingSettingsScreen/periodic_playback_session_update_frequency_editor.dart
  lib/components/PlaybackReportingSettingsScreen/play_on_reconnection_delay_editor.dart
  lib/components/PlaybackReportingSettingsScreen/play_on_stale_delay_editor.dart
  lib/components/PlaybackReportingSettingsScreen/report_queue_to_server_toggle.dart
  lib/components/PlayerScreen/feature_chips.dart
  lib/components/PlayerScreen/output_panel.dart
  lib/components/PlayerScreen/queue_source_helper.dart
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/models/finamp_models.dart
  lib/models/finamp_models.g.dart
  lib/models/jellyfin_models.dart
  lib/models/jellyfin_models.g.dart
  lib/screens/audio_service_settings_screen.dart
  lib/screens/playback_reporting_settings_screen.dart
  lib/screens/player_screen.dart
  lib/screens/settings_screen.dart
  lib/services/favorite_provider.dart
  lib/services/favorite_provider.g.dart
  lib/services/finamp_settings_helper.dart
  lib/services/finamp_settings_helper.g.dart
  lib/services/jellyfin_api.chopper.dart
  lib/services/jellyfin_api.dart
  lib/services/jellyfin_api_helper.dart
  lib/services/music_player_background_task.dart
  lib/services/playback_history_service.dart
  lib/services/playon_service.dart
  lib/services/queue_service.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, playback, playback reporting, redesign-beta

#1158 Translations update from Hosted Weblate
  lib/l10n/app_ar.arb
  lib/l10n/app_bg.arb
  lib/l10n/app_ca.arb
  lib/l10n/app_cs.arb
  lib/l10n/app_da.arb
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_et.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_hi.arb
  lib/l10n/app_hr.arb
  lib/l10n/app_hu.arb
  lib/l10n/app_it.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_pt_BR.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sv.arb
  lib/l10n/app_szl.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_th.arb
  lib/l10n/app_tr.arb
  lib/l10n/app_uk.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_Hant.arb
  lib/l10n/app_zh_Hant_HK.arb
Labels: hackathon

#1191 Fix crash in MediaItemContentProvider when the pipe breaks
  android/app/build.gradle
  android/app/src/main/kotlin/com/unicornsonlsd/finamp/MediaItemContentProvider.kt
Labels: bug, redesign-beta
