Repository jmshrv/finamp, pull requests merged in 2025-03, with the labels that each got.

#1094 Use download base directory constant for cleanup
  lib/services/downloads_service.dart
Labels: bug, redesign-beta

#1095 Rename DownloadItemType.track back to song
  lib/components/AlbumScreen/track_list_tile.dart
  lib/components/AlbumScreen/track_menu.dart
  lib/components/DownloadsScreen/item_file_size.dart
  lib/models/finamp_models.dart
  lib/models/finamp_models.g.dart
  lib/services/downloads_service.dart
  lib/services/downloads_service_backend.dart
Labels: bug, redesign-beta

#1118 Redesign downloads screen to group items by type and sort them
  lib/components/DownloadsScreen/downloaded_items_list.dart
  lib/l10n/app_en.arb
  lib/models/finamp_models.dart
  lib/screens/downloads_screen.dart
  lib/services/downloads_service.dart
Labels: enhancement, design, redesign-beta

#1130 Remove blank space when 'show album before lyrics' is disabled
  lib/l10n/app_en.arb
  lib/screens/lyrics_screen.dart
Labels: design, redesign-beta, hackathon

#1135 Always allow playlist deletion
  lib/services/jellyfin_api_helper.dart
Labels: enhancement, redesign-beta, hackathon

#1137 Fix bottom sheets on foldables
  lib/components/PlayerScreen/queue_button.dart
  lib/components/PlayerScreen/queue_list.dart
  lib/components/themed_bottom_sheet.dart
  lib/screens/lyrics_screen.dart
  lib/screens/player_screen.dart
  lib/services/display_features_helper.dart
Labels: bug, redesign-beta, hackathon
